version: "3.7"

services:
  phpliteadmin:
    hostname: phpliteadmin
    container_name: ${CONTAINER_NAME}-phpliteadmin
    image: vtacquet/phpliteadmin
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db:/db
    ports:
      - "${PHPLITEADMIN_PORT}:80"
    networks:
      - internal
    environment:
      - TZ=Europe/Brussels
      - PASSWORD=${PHPLITEADMIN_PASSWORD}
      - LOCATION=/db

networks:
  internal:
    driver: bridge
